lavender: releasetools: Cleanup and add incremental support
* Removed unused TrustZone asserts
* Fixes error: AttributeError: 'DeviceSpecificParams' object has no attribute 'input_zip'

Signed-off-by: Martin Štrobl <recordyletsplays@gmail.com>
Signed-off-by: pix106 <sbordenave@gmail.com>